In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
colnames=['data0','data1', 'data2','data3','rmFlag']
#           ,'data4','data5', 'data6','data7'] 
df = pd.read_csv("../data/test_data.txt",names=colnames,
                 skip_blank_lines=False,header=None)
print(df.head())
rows = df.shape[0]
for row in range(0,rows):
    print(df.iloc[row,0])
    print(row)
    if isinstance(df.iloc[row,0], str)==False:
        print("flag")
        df.iloc[row-2,1]=df.iloc[row-1,0]
        df.iloc[row-1,4] = 1
print(df)

                                             data0  data1  data2  data3  \
0       ecl:gry pid:860033327 eyr:2020 hcl:#fffffd    NaN    NaN    NaN
1              byr:1937 iyr:2017 cid:147 hgt:183cm    NaN    NaN    NaN
2                                              NaN    NaN    NaN    NaN
3  iyr:2013 ecl:amb cid:350 eyr:2023 pid:028048884    NaN    NaN    NaN
4                             hcl:#cfa07d byr:1929    NaN    NaN    NaN

   rmFlag
0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
ecl:gry pid:860033327 eyr:2020 hcl:#fffffd
0
byr:1937 iyr:2017 cid:147 hgt:183cm
1
nan
2
flag
iyr:2013 ecl:amb cid:350 eyr:2023 pid:028048884
3
hcl:#cfa07d byr:1929
4
nan
5
flag
hcl:#ae17e1 iyr:2013
6
eyr:2024
7
ecl:brn pid:760753108 byr:1931
8
hgt:179cm
9
nan
10
flag
hcl:#cfa07d eyr:2025 pid:166559648
11
iyr:2011 ecl:brn hgt:59in
12
                                              data0  \
0        ecl:gry pid:860033327 eyr:2020 hcl:#fffffd
1               byr:1937 iyr:2017 cid:147 hgt:183cm
2                                               NaN
3   iyr:2013 ecl:amb cid:350 eyr:2023 pid:028048884
4                              hcl:#cfa07d byr:1929
5                                               NaN
6                              hcl:#ae17e1 iyr:2013
7                                          eyr:2024
8                    ecl:brn pid:760753108 byr:1931
9                                         hgt:179cm
10                                              NaN
11               hcl:#cfa07d eyr:2025 pid:166559648
12                        iyr:2011 ecl:brn hgt:59in

                                  data1  data2  data3  rmFlag
0   byr:1937 iyr:2017 cid:147 hgt:183cm    NaN    NaN     NaN
1                                   NaN    NaN    NaN     1.0
2                                   NaN    NaN    NaN     NaN
3                  hcl:#cfa07d byr:1929    NaN    NaN     NaN
4                                   NaN    NaN    NaN     1.0
5                                   NaN    NaN    NaN     NaN
6                                   NaN    NaN    NaN     NaN
7                                   NaN    NaN    NaN     NaN
8                             hgt:179cm    NaN    NaN     NaN
9                                   NaN    NaN    NaN     1.0
10                                  NaN    NaN    NaN     NaN
11                                  NaN    NaN    NaN     NaN
12                                  NaN    NaN    NaN     NaN

In [3]:
df1 = df[df.rmFlag != 1]
rows = df1.shape[0]
for row in range(0,rows):
    print(df1.iloc[row,0])
    print(row)
    if isinstance(df1.iloc[row,0], str)==False:
        print("flag")
        df1.iloc[row-2,2]=df1.iloc[row-1,0]
        df1.iloc[row-1,4] = 1
print(df1)

ecl:gry pid:860033327 eyr:2020 hcl:#fffffd
0
nan
1
flag
iyr:2013 ecl:amb cid:350 eyr:2023 pid:028048884
2
nan
3
flag
hcl:#ae17e1 iyr:2013
4
eyr:2024
5
ecl:brn pid:760753108 byr:1931
6
nan
7
flag
hcl:#cfa07d eyr:2025 pid:166559648
8
iyr:2011 ecl:brn hgt:59in
9
                                              data0  \
0        ecl:gry pid:860033327 eyr:2020 hcl:#fffffd
2                                               NaN
3   iyr:2013 ecl:amb cid:350 eyr:2023 pid:028048884
5                                               NaN
6                              hcl:#ae17e1 iyr:2013
7                                          eyr:2024
8                    ecl:brn pid:760753108 byr:1931
10                                              NaN
11               hcl:#cfa07d eyr:2025 pid:166559648
12                        iyr:2011 ecl:brn hgt:59in

                                  data1  \
0   byr:1937 iyr:2017 cid:147 hgt:183cm
2                                   NaN
3                  hcl:#cfa07d byr:1929
5                                   NaN
6                                   NaN
7                                   NaN
8                             hgt:179cm
10                                  NaN
11                                  NaN
12                                  NaN

                                              data2  data3  rmFlag
0                                               NaN    NaN     1.0
2   iyr:2013 ecl:amb cid:350 eyr:2023 pid:028048884    NaN     NaN
3                                               NaN    NaN     1.0
5                                               NaN    NaN     NaN
6                                               NaN    NaN     NaN
7                    ecl:brn pid:760753108 byr:1931    NaN     NaN
8                                               NaN    NaN     1.0
10                                              NaN    NaN     NaN
11                                              NaN    NaN     NaN
12       ecl:gry pid:860033327 eyr:2020 hcl:#fffffd    NaN     NaN

/home/boo/miniconda3/envs/advent/lib/python3.7/site-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)